---
title: "G920_Lab2_Fastovich"
author: "David Fastovich"
output: html_document
css: style.css
---

```{r, echo=FALSE, include=FALSE}
library(rioja)
```

**Reading in the CSV file for Lake Tulane and preparing the data for plotting.**
```{r}
tul.poll <- read.csv("lake_tulane_poll.csv", skip = 9, header = TRUE) # Loading in CSV
tul.poll.t <- t(tul.poll[,-c(1:5)]) # Transposing the data into the structure we want
colnames(tul.poll.t) <- tul.poll[,1] # Adding column names for the taxa
tul.poll.t[is.na(tul.poll.t)] <- 0 # Removing NA's
```

**Making pollen counts into percentages and keeping taxa with a percentage greater than 5 that occurs at least twice in the record.**
```{r}
tul.perc <- (tul.poll.t/rowSums(tul.poll.t))*100 # Converting to percents
inclusion <- apply(tul.perc, 2, function(x) (sum(x>5))>1) # Indexing the Lake Tulane data to determine which taxa have pollen abundances greater than 5% twice
tul.perc.final <- tul.perc[,inclusion] # Applying the index and keeping the taxa that meet the above requirement
```

**Getting Depths from the CSV that were ommitted initially.**
```{r}
tul.all <- read.csv("lake_tulane_poll.csv") # Pulling in the data again, but this time not excluding the frist 9 rows as those include depth
tul.depth <- as.numeric(as.character(unlist(tul.all[2,-c(1:5)]))) # Extracting the depth from the above data frame
```

**Plotting pollen diagram for Lake Tulane with Depth**
```{r}
strat.plot(tul.perc.final, yvar = tul.depth, scale.percent = TRUE, y.rev = TRUE) # Plotting the pollen diagram
```